### ISSUE TITLE
logo cropping - svg, jpg, png

### ISSUE THREAD

**Issue by R-Walther** [ricotomo/StudEUWebsite#50]

**Comment by ricotomo** [comment]
![image](https://user-images.githubusercontent.com/18460423/89460002-deef8b00-d769-11ea-8e70-84649101d705.png)

**Comment by ricotomo** [comment]
These are the specifications from medium. Im adding you as an editor so you should be able to upload the Logo to Medium directly

**Comment by ricotomo** [comment]
Not sure using a publication is going to work. Im using the pixelpoint medium widget to get and display our posts. It doesnt seem to render the publication content
